apiVersion: apps/v1
kind: Deployment
metadata:
  name: breeze
  namespace: breeze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breeze
  template:
    metadata:
      labels:
        app: breeze

    spec:
      volumes:
        - name: gpio-mem
          hostPath:
            path: /dev/gpiomem
        - name: gpio
          hostPath:
            path: /sys/class/gpio
        - name: gpio-chip0
          hostPath:
            path: /dev/gpiochip0
      containers:
        - name: breeze
          image: garugaru/breeze:arm-latest
          command: ["breeze", "controller"]
          imagePullPolicy: Always
          ports:
            - containerPort: 9999
          volumeMounts:
            - name: gpio-mem
              mountPath: /dev/gpiomem
            - name: gpio
              mountPath: /sys/class/gpio
            - name: gpio-chip0
              mountPath: /dev/gpiochip0
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "5Mi"
              cpu: "10m"
            limits:
              memory: "15Mi"
              cpu: "10m"

