apiVersion: v1
kind: Service
metadata:
  name: breeze
  namespace: breeze
  labels:
    app: breeze
spec:
  ports:
    - name: metrics
      port: 9999
      targetPort: 9999

  selector:
    app: breeze
