apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: breeze
  namespace: prometheus
  labels:
    release: prometheus-operator
    app: breeze
spec:
  namespaceSelector:
    matchNames:
      - breeze
  selector:
    matchLabels:
      app: breeze
  endpoints:
    - port: metrics
      path: /metrics
